/* generated by tools/gen_audio_stubs.py: Miles Sound System and Bink in "no audio device" mode (the game runs
 * silently and skips videos); a Core Audio implementation replaces these later. */
#include "w32.h"
static uint32_t no_audio_msg(void) { static uint32_t s; if (!s) { s = heap_alloc(w32_process_heap, 8, 64); strcpy((char *)GP(s), "No audio device (native port: audio not implemented yet)"); } return s; }
IMPL(binkw32, BinkClose) { static int n; if (getenv("W32_AUDIOLOG") && n++ < 3) fprintf(stderr, "audio: BinkClose\n"); RET(0, 1); }
IMPL(binkw32, BinkCopyToBuffer) { static int n; if (getenv("W32_AUDIOLOG") && n++ < 3) fprintf(stderr, "audio: BinkCopyToBuffer\n"); RET(0, 7); }
IMPL(binkw32, BinkDoFrame) { static int n; if (getenv("W32_AUDIOLOG") && n++ < 3) fprintf(stderr, "audio: BinkDoFrame\n"); RET(0, 1); }
IMPL(binkw32, BinkNextFrame) { static int n; if (getenv("W32_AUDIOLOG") && n++ < 3) fprintf(stderr, "audio: BinkNextFrame\n"); RET(0, 1); }
IMPL(binkw32, BinkOpen) { static int n; if (getenv("W32_AUDIOLOG") && n++ < 3) fprintf(stderr, "audio: BinkOpen\n"); RET(0, 2); }
IMPL(binkw32, BinkOpenMiles) { static int n; if (getenv("W32_AUDIOLOG") && n++ < 3) fprintf(stderr, "audio: BinkOpenMiles\n"); RET(0, 1); }
IMPL(binkw32, BinkPause) { static int n; if (getenv("W32_AUDIOLOG") && n++ < 3) fprintf(stderr, "audio: BinkPause\n"); RET(0, 2); }
IMPL(binkw32, BinkSetSoundSystem) { static int n; if (getenv("W32_AUDIOLOG") && n++ < 3) fprintf(stderr, "audio: BinkSetSoundSystem\n"); RET(1, 2); }
IMPL(binkw32, BinkSetSoundTrack) { static int n; if (getenv("W32_AUDIOLOG") && n++ < 3) fprintf(stderr, "audio: BinkSetSoundTrack\n"); RET(0, 1); }
IMPL(binkw32, BinkWait) { static int n; if (getenv("W32_AUDIOLOG") && n++ < 3) fprintf(stderr, "audio: BinkWait\n"); RET(0, 1); }
