"""gen_audio_stubs.py <exe> <out.c>: Miles (mss32) and Bink (binkw32) entry points for the "no audio device" mode,
with stdcall argument counts taken from the decorated import names (_Name@bytes)."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__)); from pe import PE
pe = PE(sys.argv[1])
ret = {   # explicit results; everything else returns 0
    'AIL_startup': '1', 'AIL_register_timer': '0xffffffffu', 'AIL_last_error': 'no_audio_msg()',
    'AIL_set_redist_directory': 'no_audio_msg()', 'BinkSetSoundSystem': '1',
}
out = ['/* generated by tools/gen_audio_stubs.py: Miles Sound System and Bink in "no audio device" mode (the game runs\n'
       ' * silently and skips videos); a Core Audio implementation replaces these later. */',
       '#include "w32.h"',
       'static uint32_t no_audio_msg(void) { static uint32_t s; if (!s) { s = heap_alloc(w32_process_heap, 8, 64); strcpy((char *)GP(s), "No audio device (native port: audio not implemented yet)"); } return s; }']
for va, name in sorted(pe.imports.items(), key=lambda kv: kv[1]):
    dll, fn = name.split('!')
    if dll.lower() not in ('binkw32.dll',): continue                # Miles: runtime/win32/miles.c
    base, nbytes = fn.lstrip('_').split('@')
    d = 'mss32' if dll.lower() == 'mss32.dll' else 'binkw32'
    out.append('IMPL(%s, %s) { static int n; if (getenv("W32_AUDIOLOG") && n++ < 3) fprintf(stderr, "audio: %s\\n"); RET(%s, %d); }' % (d, base, base, ret.get(base, '0'), int(nbytes) // 4))
open(sys.argv[2], 'w').write('\n'.join(out) + '\n')
print('%d entry points' % (len(out) - 3))
